name: Build and Publish CUDA Images

on:
  push:
    branches: [main]
  # workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * 0'  # Weekly on Sundays

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install deps
        run: pip install dagger-io

      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }

      - name: Convert repository owner to lowercase
        run: |
          echo "REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Run dagger pipeline
        run: python main.py
        env:
          USERNAME: ${{ env.REPOSITORY_OWNER }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.event.repository.name }}
